### ISSUE TITLE
doesn't work with `emacs-ng`

### ISSUE THREAD

**Issue by Tanish2002** [nix-community/nix-doom-emacs#122]
I tried to use emacs-ng as the emacsPackage but it gets stuck at installation.
SC:
![image](https://user-images.githubusercontent.com/55488165/166146850-b8f7b168-54b6-4bd3-a380-645a8ff0c777.png)

I can use emacs-ng normally using `nix run github:emacs-ng/emacs-ng`.
Here is my config
```nix
{ pkgs, inputs, config, ... }: {
  programs.doom-emacs = {
    enable = true;
    doomPrivateDir = ./doom.d;
    emacsPackage = inputs.emacs-ng.packages.x86_64-linux.default;
  };
  services.emacs.enable = true;
}
```
here emacs-ng is a flake input `emacs-ng.url = "github:emacs-ng/emacs-ng";`

**Comment by bobbbay** [comment]
Have you tried building off the [binary cache](https://emacs-ng.github.io/emacs-ng/build/nix-develop/#using-cachix-to-download-binary-cache-speed-up-build)? Try installing Cachix and running `cachix use emacsng`.

**Comment by Tanish2002** [comment]
@bobbbay I believe I am using binary cache, as you can see in the screenshot I am using binary cache by using `extra-substituters` and `extra-trusted-public-keys`

**Comment by ckiee** [comment]
It getting stuck seems unusual. Maybe ask Nix to be more verbose? I dunno and I don't support `emacs-ng` so it's up to you to figure out why it's broken, though I'm open for a chat on matrix if you get stuck: [`@ckie:ckie.dev`](https://matrix.to/#/@ckie:ckie.dev).

**Comment by Tanish2002** [comment]
well fwiw here's the screenshot of verbose build
![image](https://user-images.githubusercontent.com/55488165/167828517-e596ecc5-6878-4847-abd0-77846231f057.png)

**Comment by thiagokokada** [comment]
Marking this as wontfix. `emacs-ng` is really different from `emacs`.

Also, I don't think upstream supports it neither.
