### ISSUE TITLE
Flake fails to build with default install options

### ISSUE THREAD

**Issue by remi-gelinas** [nix-community/nix-doom-emacs#133]
I tried to add `doom-emacs` into my `nix-darwin` flake as shown in the readme (as I would any other `home-manager` module), which can be found [here](https://github.com/remi-gelinas/nixpkgs/commit/ed1b7eaed09ffc204d2c9c6aeb0070c16f706478) at the broken commit.

Upon install `doom-emacs` is failing to build the `emacs` derivation with extra packages, the build fails when installing extra packages with `nix-straight`, this being the main excerpt of the trace:

```
(file-error "Creating directory")

(signal file-error ("Creating directory" "Permission denied" "/nix/store/y0rwwmkxvw7isb81g9x6nipyb8i4lwq4-doom-src/Executing git is not allowed; command line: rev-parse --git    -path hooks"))

(files--ensure-directory "/nix/store/y0rwwmkxvw7isb81g9x6nipyb8i4lwq4-doom-src/executing git is not allowed; command line: rev-parse --git-path hooks")

(make-directory "executing git is not allowed; command line: rev-parse --git-path hooks" parents)
```

The full trace is available in a Gist [here](https://gist.github.com/remi-gelinas/ca51b5eb59f3aca7d765679d6cf8d9c2).

I haven't done anything past enable the `doom-emacs` program in `home-manager` and supply a path to a copy-pasted version of `test/doom.d`, as I do not have any previous config and am starting from scratch.

On first glance this seems like a permissions issue in the nix store during build, or a lack of git as a build dependency somewhere, but I have not added any extra packages, and I would expect an error along the lines of `command 'git' could not be found"` if that were the case.

Has anyone else run into this on a fresh flake install?

**Comment by ckiee** [comment]
Does `nix flake check` in this repo's root succeed for you? Also, that error is [our own doing](https://github.com/nix-community/nix-doom-emacs/blob/6860a32b4bb158db85371efd7df0fe35ebcecb9b/default.nix#L142) but that code is older than I've been maintaining this.

**Comment by remi-gelinas** [comment]
No, a fresh `master` clone and `nix flake check` results in this trace:

```
❯ nix flake check
warning: flake output attribute 'devShell' is deprecated; use 'devShells.<system>.default' instead
warning: unknown flake output 'package'
error: a 'x86_64-linux' with features {} is required to build '/nix/store/vawsyzi4fkn0m9dbsmkl9smg8wb1xnp6-fix-paths.patch.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
```

Is this flake not compatible with M1 Mac machines yet?

**Comment by starcraft66** [comment]
It works fine on M1, your issue is that your nix installation is aarch64-darwin but you imported an x86_64-darwin nixpkgs.

**Comment by starcraft66** [comment]
Actually upon further inspection, the devShell might indeed be broken as it is hardcoded to an old default architecture. nix-doom-emacs, however, definitely works on apple silicon.

**Comment by ckiee** [comment]
> Is this flake not compatible with M1 Mac machines yet?

The checks weren't, buut now they are: https://github.com/nix-community/nix-doom-emacs/commit/edbe868

**Comment by remi-gelinas** [comment]
> 

With my local HEAD matching `edbe868dd5f8bf447eaffd4cff85167d0771ce0f`, I get the same error trying to check the flake, oddly enough.

```
warning: flake output attribute 'devShell' is deprecated; use 'devShells.<system>.default' instead
warning: unknown flake output 'package'
error: a 'x86_64-linux' with features {} is required to build '/nix/store/kzsr6ifif0ldzr6qrn57d8lm1j4rb2rm-fix-paths.patch.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
```
