### ISSUE TITLE
CI fails on latest commit, which has killed github actions

### ISSUE THREAD

**Issue by bootstrap-prime** [nix-community/nix-doom-emacs#142]
```
a 'aarch64-darwin' with features {} is required to build '/nix/store/sq8ppka3wyih94gx79qhkawkdsiadlif-fix-paths.patch.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, nixos-test, recursive-nix}
```
You may need to reconfigure the build server to support cross compilation, if that's possible. If it's not possible, you may be able to have two separate actions for each arch that run checks on their respective arches?

**Comment by starcraft66** [comment]
It's certainly possible for linux, I've done it with the install QEMU action on GH. I'm unsure if it works on OSX however, as GitHub doesn't provide any hosted apple silicon runners.
