### ISSUE TITLE
Doom fails to build

### ISSUE THREAD

**Issue by DearRude** [nix-community/nix-doom-emacs#184]
After [this](https://github.com/nix-community/nix-doom-emacs/commit/96209801150e898e080d75e571403a48cad05b21) commit, dooms fails to build with the following error:
```
Single file ghub-pkg.el does not match package name ghub
builder for '/nix/store/p1g1i94fwf88998sqvvf56g14rpghf5j-emacs-ghub-20220429.1708.drv' failed with exit code 255
```

**Comment by ckiee** [comment]
The test configuration in this repo builds fine, excluding an issue with codeberg being down recently, but you aren't hitting that. Good luck.
