### ISSUE TITLE
`SPC *` (+default/search-project-for-symbol-at-point SYMBOL DIR) not working with `vertico` 

### ISSUE THREAD

**Issue by thiagokokada** [nix-community/nix-doom-emacs#185]
I recently migrated to `nix-doom-emacs`, and while on `doom-emacs` itself the `SPC *` works, in `nix-doom-emacs` it doesn't. I tried both Emacs 28.1 and 29.0.50, with the same results.

I get the following error: `cond: Keyword argument :function not one of (:type :separator :initial)`. Maybe this is one of those packages that `doom-emacs` uses a fork, and we also need to overlay with the fork :thinking: ?

My HM Emacs config is located [here](https://github.com/thiagokokada/nix-configs/tree/master/home-manager/emacs). I use `vertico` as my completion engine, but not sure if related.

**Comment by thiagokokada** [comment]
Changing from `vertico` to `ivy` did fix it. So I think maybe the issue is on `vertico` after all :thinking: ?

**Comment by ckiee** [comment]
We're probably just using the wrong version of *something*. Try with upstream doom, see if that works, and if it doesn't you can make a PR to add the package to `overrides.nix`. Good luck.

**Comment by thiagokokada** [comment]
It definitively works in Doom itself.

Yeah, once I have more time I will try to investigate this further. For now using `ivy` is fine.

**Comment by thiagokokada** [comment]
So updating all my flake inputs and adding `doom-emacs` to my flake and adding it as a `nix-doom-emacs.inputs.doom-emacs.follows = "doom-emacs"` seems to do the trick: https://github.com/thiagokokada/nix-configs/commit/2bdf691a780d2ae3ecfa436aab01d5c752150f04. I think the problem is either some plugin that was broke and now it is fixed, or that the `doom-emacs` pin from this repo is old enough to cause the issue.

Anyway, closing this issue.
