### ISSUE TITLE
Home-Manager module should include `~/.emacs.d/early-init.el` file

### ISSUE THREAD

**Issue by thiagokokada** [nix-community/nix-doom-emacs#186]
Starting Doom-Emacs using this project shows Emacs ugly default theme until the load of `~/.emacs.d/init.el` happens (that loads the `site-lisp`). Doom-Emacs itself solves this problems by adding a `~/.emacs.d/early-init.el` file, that changes a few things during Emacs initialization so the load of the rest of the code works smoothly (and probably faster too). This projects [loads](https://github.com/nix-community/nix-doom-emacs/blob/master/default.nix#L209-L210) the [`early-init.el`](https://github.com/doomemacs/doomemacs/blob/master/early-init.el) shipped by upstream, but it only loads it after the initial load, so this doesn't really help.

Instead, the Home-Manager module should also link upstream `early-init.el` file to the `~/.enacs.d/early-init.el` location, so we can have its benefits. Sadly we will probably need to patch the original file, since I tried to use as-is but it didn't work (I think because of this [line](https://github.com/doomemacs/doomemacs/blob/master/early-init.el#L76) that tries to load the rest of Doom-Emacs from `~/.emacs.d` directory). I actually removed all the [bootstrap part of that file in my personal configuration](https://github.com/thiagokokada/nix-configs/commit/99d366ee3680a8c5ec70d3fb98f9508b364bfc65) and it works, but probably this is not the best way to go.

**Comment by thiagokokada** [comment]
One minor issue: https://github.com/nix-community/nix-doom-emacs/blob/master/default.nix#L209-L210

We can probably remove this check for Emacs version, since Doom-Emacs doesn't support anything lower than Emacs 27.1 anyway.

**Comment by ckiee** [comment]
Feel free to make a patch.

**Comment by thiagokokada** [comment]
Fixed by https://github.com/nix-community/nix-doom-emacs/pull/191.
