### ISSUE TITLE
can't Install copilot.el using `emacsPackagesOverlay`

### ISSUE THREAD

**Issue by Tanish2002** [nix-community/nix-doom-emacs#212]
I'm trying to install [copilot.el](https://github.com/zerolfx/copilot.el) but having problems.
My config to install it
```nix
    emacsPackagesOverlay = self: super: {
      copilot = self.trivialBuild {
        pname = "copilot";
        ename = "copilot";
        version = "0.1.0";
        src = self.fetchFromGithub {
          repo = "copilot.el";
          owner = "zerolfx";
          rev = "9b13478720581580a045ac76ad68be075466a963";
          sha256 = "sha256-csY9dxUpTw6hWwL+JJnNOsbLNlToIfh/gsdxS1uEQtg";
        };
        buildInputs = [ pkgs.nodejs ];
      };
    };
```

**Comment by voobscout** [comment]
Just set the **copilot--base-dir** variable to the src derivation, [look here for reference](https://github.com/zerolfx/copilot.el/blob/5b6f984efdd81356e6f43b80d14a99bcae201737/copilot.el#L104).

```nix
{ pkgs, ... }:

{
  programs.doom-emacs.emacsPackagesOverlay = self: super: {
    copilot = self.trivialBuild {
      inherit (pkgs.sources.copilot-el) pname version src;
      ename = "copilot";
      buildInputs = with pkgs; [ nodejs ];
      packageRequires = with self; [ s dash editorconfig ];
    };
  };

  home.sessionVariables.EMACS_PATH_COPILOT = "${pkgs.sources.copilot-el.src}";
  home.packages = [ pkgs.nodejs ];
}
```

* packages.el
```emacs-lisp
(package! copilot)
```

* config.el
```emacs-lisp
(use-package! copilot
  :config (setq copilot--base-dir (getenv "EMACS_PATH_COPILOT"))
  :hook (prog-mode . copilot-mode)
  :bind (("C-TAB" . 'copilot-accept-completion-by-word)
         ("C-<tab>" . 'copilot-accept-completion-by-word)
         :map copilot-completion-map
         ("<tab>" . 'copilot-accept-completion)
         ("TAB" . 'copilot-accept-completion)))
```

**Comment by Tanish2002** [comment]
Thanks! That worked

**Comment by sepiabrown** [comment]
> Just set the **copilot--base-dir** variable to the src derivation, [look here for reference](https://github.com/zerolfx/copilot.el/blob/5b6f984efdd81356e6f43b80d14a99bcae201737/copilot.el#L104).
> 
> ```nix
> { pkgs, ... }:
> 
> {
>   programs.doom-emacs.emacsPackagesOverlay = self: super: {
>     copilot = self.trivialBuild {
>       inherit (pkgs.sources.copilot-el) pname version src;
>       ename = "copilot";
>       buildInputs = with pkgs; [ nodejs ];
>       packageRequires = with self; [ s dash editorconfig ];
>     };
>   };
> 
>   home.sessionVariables.EMACS_PATH_COPILOT = "${pkgs.sources.copilot-el.src}";
>   home.packages = [ pkgs.nodejs ];
> }
> ```
> 
> * packages.el
> 
> ```emacs-lisp
> (package! copilot)
> ```
> 
> * config.el
> 
> ```emacs-lisp
> (use-package! copilot
>   :config (setq copilot--base-dir (getenv "EMACS_PATH_COPILOT"))
>   :hook (prog-mode . copilot-mode)
>   :bind (("C-TAB" . 'copilot-accept-completion-by-word)
>          ("C-<tab>" . 'copilot-accept-completion-by-word)
>          :map copilot-completion-map
>          ("<tab>" . 'copilot-accept-completion)
>          ("TAB" . 'copilot-accept-completion)))
> ```

Thank you!

**Comment by Velnbur** [comment]
Strange, but I've got no `sources` in `nixpkgs`.
