### ISSUE TITLE
`doom-etc-dir` is set incorrectly. Volatile files pollute `~/.local`.

### ISSUE THREAD

**Issue by azahi** [nix-community/nix-doom-emacs#247]
Current configuration pollutes user's `~/.local` dir without creating a specific `doom` directory. On my machine it looks something like this:
```
[azahi@melian:~/.local]$ l
total 12K
drwxr-xr-x  11 azahi users  182 Aug 17 12:24 .
drwx------+ 29 azahi users 4.0K Aug 17 13:12 ..
drwxr-xr-x   2 azahi users   73 Jul 13 00:30 bin
drwxr-xr-x   2 azahi users    6 Aug 17 11:41 doom
-rw-r--r--   1 azahi users   81 Aug 17 12:32 doomdap-breakpoints
drwx------   2 azahi users   21 Aug 17 11:40 doomeshell
drwxr-xr-x   2 azahi users   35 Aug 17 11:38 doomforge
drwxr-xr-x   2 azahi users   36 Aug 15 23:54 doomparinfer-rust
drwxr-xr-x   2 azahi users   26 Aug 15 23:57 doomscratch
drwxr-xr-x   2 azahi users   21 Aug 16 11:32 doomtransient
drwxr-xr-x  45 azahi users 4.0K Aug 17 13:18 share
drwx------   4 azahi users   56 Mar  5 11:25 state
```

I'm assuming this is happening because of an incorrectly patched Nix integration [here](https://github.com/nix-community/nix-doom-emacs/blob/20ca56a17dc33d67ed7d61b0e84205c617394b5b/patches/nix-integration.patch#L129-L130). I'm guessing it should be something like this instead (note the trailing `/`):
```diff
-    (concat doom-local-dir "etc/"))
+    "~/.local/doom/")
```

However, I might be wrong about that because the same doesn't happen with the `~/.cache/doom` directory.

The second part of the issue is that these paths are essentially hardcoded. Wouldn't it be better if we could somehow use XDG specification for these instead?

**Comment by thiagokokada** [comment]
@azahi Opened a PR: https://github.com/nix-community/nix-doom-emacs/pull/248

Can you test and check if it solves your issue?
