### ISSUE TITLE
Support requests are mixed in with bugs

### ISSUE THREAD

**Issue by ckiee** [nix-community/nix-doom-emacs#252]
@thiagokokada I got pinged in #nix:nixos.org today by someone asking for help with nde and after I answered their question another person popped up in the room almost immediately also trying to use this project. 

A lot of the issues we get are sort of repetitive. Do you think we should make a matrix room and stick it in the README? I'm not really convinced either way:
` +` maybe people will help each other more casually, then we don't get as many emails and don't have to write as many responses.
` -` questions will get repeatedly brought up, and unlike here, will have to be answered many times since matrix does not really have the nice searchable discussion UX GitHub does.

Thoughts?

**Comment by thiagokokada** [comment]
Sure.

I mean, I am not the most active person in Matrix and will probably not be very active there. But I also think it is better than folks posting messages in random channels/issues.

**Comment by Lord-Valen** [comment]
It's better than issue clutter. But since you're seeing repetetive questions... why not make an FAQ?

**Comment by MonAaraj** [comment]
I agree for both a FAQ and some sort of chatting room. Some sort of nix-community Matrix room might be good.

**Comment by MonAaraj** [comment]
Do you think this issue should be closed by now? I think it's mostly fixed, and when https://github.com/nix-community/nix-doom-emacs/pull/266 is merged, we should also be able to refer to the documentation for a lot of questions

**Comment by thiagokokada** [comment]
> Do you think this issue should be closed by now? I think it's mostly fixed, and when #266 is merged, we should also be able to refer to the documentation for a lot of questions

Let's leave this open until #266 is merged. Also I will probably will go and close all support related issues and redirect its creators to the Matrix chat too.

**Comment by akaihola** [comment]
#266 seems to have been merged last week.

Is [#doom-emacs:nixos.org](https://matrix.to/#/#doom-emacs:nixos.org) now _the_ place to ask for help? Is creating an FAQ now the other task to be completed for this issue?

**Comment by ckiee** [comment]
#266 also brought an FAQ along, see [`/docs`](https://github.com/nix-community/nix-doom-emacs/tree/master/docs).

> Is [#doom-emacs:nixos.org](https://matrix.to/#/#doom-emacs:nixos.org) now _the_ place to ask for help?

*the* seems like a lot; vaguely depends on whether you think you have an *issue* issue or a "I'm sure there's this really easy way to do this" issue where you're just optimizing for minimal effort -- that also overlaps with the FAQ.

I don't think it's worth trying to codify that. There's a few options to choose from as you wish, I think.

**Comment by ribosomerocker** [comment]
I suppose this should be closed, then?

**Comment by ckiee** [comment]
sure! ❤️
