### ISSUE TITLE
Issue with nix-integration patch

### ISSUE THREAD

**Issue by JonathanLorimer** [nix-community/nix-doom-emacs#28]
I am getting this error when trying to build with doom emacs
```
error: builder for '/nix/store/hyj2kcmy4drv69sqxizrdfkbmcags5mn-doom-emacs.drv' failed with exit code 1;
       last 10 log lines:
       > unpacking source archive /nix/store/2lmhr049hzn5fvgl0cgbwfdn59f1raaz-doom-src
       > source root is doom-src
       > patching sources
       > applying patch /nix/store/wl3gb8p4r0zla1y3k2l76r98i4sn1j7q-nix-integration.patch
       > patching file core/core-cli.el
       > patching file core/core.el
       > Hunk #1 FAILED at 68.
       > Hunk #2 succeeded at 82 (offset 6 lines).
       > Hunk #3 FAILED at 160.
       > 2 out of 3 hunks FAILED -- saving rejects to file core/core.el.rej
       For full logs, run 'nix log /nix/store/hyj2kcmy4drv69sqxizrdfkbmcags5mn-doom-emacs.drv'.
```

**Comment by ckiee** [comment]
It seems to build for me on https://github.com/ckiee/nixfiles/commit/ab8a34c. (from master)

Can you upload your config including doom somewhere? It's much easier to debug locally and Nix lets us do that effectively (:

**Comment by JonathanLorimer** [comment]
So, I actually just cloned hlissner/doom-emacs and applied `/nix/store/wl3gb8p4r0zla1y3k2l76r98i4sn1j7q-nix-integration.patch` manually, so I am a bit lost as to why its failing when building.

**Comment by JonathanLorimer** [comment]
- Doom emacs in my home manager https://github.com/JonathanLorimer/nix-config/blob/doom-emacs/programs/default.nix#L8-L11
- Doom emacs in my flake https://github.com/JonathanLorimer/nix-config/blob/doom-emacs/flake.nix#L59
- hmModule https://github.com/JonathanLorimer/nix-config/blob/doom-emacs/jonathanl.nix#L12

**Comment by JonathanLorimer** [comment]
I also created a PR so its a bit easier to see the diff https://github.com/JonathanLorimer/nix-config/pull/2

**Comment by JonathanLorimer** [comment]
Okay, so, while I was debugging I ran `nix flake lock --update-input doom-emacs` explicitly and noticed that all of these got updated instead of just `nix-doom-emacs` (which was getting updated as I changed the rev and github sources in my `flake.nix`)

```
nixpkgs on  doom-emacs [$!]
λ nix flake lock --update-input nix-doom-emacs
warning: Git tree '/home/jonathanl/.config/nixpkgs' is dirty
warning: updating lock file '/home/jonathanl/.config/nixpkgs/flake.lock':
• Updated input 'nix-doom-emacs':
    'github:JonathanLorimer/nix-doom-emacs/2453fc69ec61d2334d9fdb2c86f1921de01352af' (2022-01-09)
  → 'github:JonathanLorimer/nix-doom-emacs/13f0225dcc3720b36b0c6fdf89f55c027984e6f9' (2022-01-09)
• Updated input 'nix-doom-emacs/doom-emacs':
    'github:hlissner/doom-emacs/46732c0adaef147144418f9f284ca6b1183ab96f' (2021-07-18)
  → 'github:hlissner/doom-emacs/bc47e72984f9e6eb89a19e9560185188575b10c1' (2022-01-06)
• Updated input 'nix-doom-emacs/doom-snippets':
    'github:hlissner/doom-snippets/5c0eb5bd70f035cefb981c2ce64f4367498bdda6' (2021-07-06)
  → 'github:hlissner/doom-snippets/3083b2342f95fa55c1fd3b4a16229c5d867a02b0' (2021-11-24)
• Updated input 'nix-doom-emacs/emacs-overlay':
    'github:nix-community/emacs-overlay/be04b45efb35db58e6ac6aa86b84f850c85b5dfe' (2021-07-22)
  → 'github:nix-community/emacs-overlay/dfa2c6f65bca313425e28ec262d0fad458c57622' (2022-01-06)
• Updated input 'nix-doom-emacs/flake-utils':
    'github:numtide/flake-utils/f7e004a55b120c02ecb6219596820fcd32ca8772' (2021-06-16)
  → 'github:numtide/flake-utils/74f7e4319258e287b0f9cb95426c9853b282730b' (2021-11-28)
• Updated input 'nix-doom-emacs/nixpkgs':
    'github:NixOS/nixpkgs/16105403bdd843540cbef9c63fc0f16c1c6eaa70' (2021-07-21)
  → 'github:NixOS/nixpkgs/77fda7f672726e1a95c8cd200f27bccfc86c870b' (2022-01-06)
• Updated input 'nix-doom-emacs/org':
    'github:emacs-straight/org-mode/c9dfed48a607c7f6524f1c6480f09cf61a5d6237' (2021-07-24)
  → 'github:emacs-straight/org-mode/d012350dadf15835e361626ba0a6ec08f8c7a715' (2021-12-25)
• Updated input 'nix-doom-emacs/org-contrib':
    'git+https://git.sr.ht/~bzg/org-contrib?ref=master&rev=fc81309cf6756607a836f93049a9393c2967c4e0' (2021-06-10)
  → 'git+https://git.sr.ht/~bzg/org-contrib?ref=master&rev=5766ff1088191e4df5fecd55007ba4271e609bcc' (2021-12-17)
• Updated input 'nix-doom-emacs/revealjs':
    'github:hakimel/reveal.js/b18f12d964ef80bd9ffb061aae48ff4c15fb43ad' (2021-07-09)
  → 'github:hakimel/reveal.js/dbb1d5ed19bdb42113d64ca452abdeaf9f92e6de' (2022-01-03)
```

Something is at least building now. This must be caused by me jumping around between too many input versions and not explicitly updating! Sorry to clutter the issue tracker, I am not really sure how to guard against this in the future.

**Comment by ulysses4ever** [comment]
Not sure how useful of an advice this would be, but I recently figured that if I don't want multiple `nixpkgs` as inputs to my modules, I  should use `follows`, e.g.:
```
   # ...
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
    nix-doom-emacs.inputs.nixpkgs.follows = "nixpkgs";
    nix-doom-emacs.inputs.emacs-overlay.follows = "emacs-overlay";
```

**Comment by JonathanLorimer** [comment]
@ulysses4ever Ahhhhh, good advice, I am definitely going to try and do that to my config.

**Comment by ckiee** [comment]
> Okay, so, while I was debugging I ran `nix flake lock --update-input doom-emacs` explicitly and noticed that all of these got updated instead of just `nix-doom-emacs` (which was getting updated as I changed the rev and github sources in my `flake.nix`)

That is probably a bad idea: the dependencies are all [tested together] before an auto flake update is pushed to master, but hey, if it works..

Anyhow, I'm building your `doom-emacs` branch now, but downloads will take a while..

**Comment by JonathanLorimer** [comment]
@ckiee I think everything is working now, all that's left to investigate is this https://github.com/nix-community/nix-doom-emacs/issues/27

**Comment by ckiee** [comment]
No, I know it works–but I don't know why.. Yet.
<hr>

```json
ckie@cookiemonster ~/git/jl-nix-config -> cat flake.lock  | jq '.nodes["nix-doom-emacs"].locked'
{
  "lastModified": 1641517873,
  "narHash": "sha256-JWiJXjrZO7WlMORT8E27QjGQYsrtS3ln5LG087bMYZg=",
  "owner": "nix-community",
  "repo": "nix-doom-emacs",
  "rev": "6f3ac60c5719171f805740558e1705d0b46f91ba",
  "type": "github"
}
```
```
ckie@cookiemonster ~/git/nix-doom-emacs -> git show "6f3ac60c5719171f805740558e1705d0b46f91ba"
fatal: bad object 6f3ac60c5719171f805740558e1705d0b46f91ba
```
The commit you were using doesn't even exist in my local checkout! That sort of explains it, and I got confused because I thought that `nix flake lock` was ignoring `nix-doom-emacs`'s `flake.lock` but it [does](https://github.com/jonathanlorimer/nix-config/blob/c990e94cf2519ec257d6b0463fe8d2994c264663/flake.lock#L327) [not](https://github.com/nix-community/nix-doom-emacs/blob/a68b5e5b323a82120cb693e188f279021fe6ae01/flake.lock#L154). I'd bet #27 is also related to the dependency mess since I had that problem before and I think a simple dependency update fixed it at the time, so I think you can close that issue too.

Also, here, have some [Sweden](https://www.youtube.com/watch?v=A1vLUFBpHm0) (:
