### ISSUE TITLE
Build native-compiles every package every time my emacs config changes.

### ISSUE THREAD

**Issue by znewman01** [nix-community/nix-doom-emacs#297]
Hi!

I use `nix-doom-emacs` [like this](https://github.com/znewman01/dotfiles/blob/98366c4aab71385c328ab28a3bbaabb3377e4bf0/emacs/default.nix#L6-L12), following the suggestion in https://github.com/nix-community/nix-doom-emacs/issues/60#issuecomment-1083630633 for tangling my literate config ([here](https://github.com/znewman01/dotfiles/blob/9174aafb6bd4d03aa8e31b7348e572cb6567a052/emacs/doom.d/default.nix)).

```nix
  programs.doom-emacs = {
    enable = true;
    doomPrivateDir = (import ./doom.d) {
      inherit lib;
      inherit (pkgs) stdenv emacs coreutils;
    };
  };
```

Every time I change my Emacs configuration at all and rebuild, it takes a *long* time while Nix recompiles every Emacs package. I have the [nix-community cachix added](https://github.com/znewman01/dotfiles/blob/98366c4aab71385c328ab28a3bbaabb3377e4bf0/common/default.nix#L5-L9), but it doesn't appear to get used at all. Not sure why.

I want to figure out the problem with cachix but in the meantime, I noticed that this rebuild happens even if the set of packages changed. I played around with it, and turns out it's pretty easy to cache the straight-env by only including `init.el` and `packages.el`: https://github.com/znewman01/nix-doom-emacs/commit/a076453f02efa5016511a0154423afd711f81d19

Would something like that be useful to commit back? It feels strictly better to me than rebuilding each time. Maybe a flag to turn off the behavior in case someone has an interesting package installation setup that relies on some other files?

For reference: my [flake.nix](https://github.com/znewman01/dotfiles/blob/98366c4aab71385c328ab28a3bbaabb3377e4bf0/flake.nix#L18-L21) (pointing at my fork of nix-doom-emacs) and [flake.lock](https://github.com/znewman01/dotfiles/blob/98366c4aab71385c328ab28a3bbaabb3377e4bf0/flake.lock#L24).

**Comment by ckiee** [comment]
It's pretty neat.

@thiagokokada:

I feel like we thought about this at one point already, maybe it just got lost in a thread? Feels like a bit of a hack but I'm up for a PR with a flag to opt out I think.

**Comment by thiagokokada** [comment]
Yeah, the idea is pretty neat, however there is a few issues that I can think of.

AFAIK, there is nothing in `doom-emacs` that prohibits you to declare packages in places that are not the `package.el` file. Also, you can create custom modules that also declare packages. So in both of those cases this idea from @znewman01 would fail to take the new packages and trigger a new build.

We probably need a way to declare the files that will trigger the rebuild, so the user can customize themselves.

**Comment by znewman01** [comment]
Yeah, you're both right—it's definitely a hack, which is why I wanted to ask before just sending a PR in. 🙂 

WDYT about something like:

- a new `doomPackageFilesDir` argument:
   ```nix
   {
     # [...]
      /* A Doom configuration directory from which to build the Emacs package environment.

         Can be used, for instance, to prevent rebuilding the Emacs environment
         each time the `config.el` changes.

         Can be provided as a directory or derivation. If not given, package
         environment is built against `doomPrivateDir`.

         Example:
           doomPackageDir = pkgs.linkFarm "my-doom-packages" [
             # straight needs a (possibly empty) `config.el` file to build
             { name = "config.el"; path = pkgs.emptyFile; }
             { name = "init.el"; path = ./doom.d/init.el; }
             { name = "packages.el"; path = pkgs.writeText "(package! inheritenv)"; }
             { name = "modules"; path = ./my-doom-module; }
           ];
      */
      doomPackageDir ? "",
      # ...
   ```

That feels okay to me for a first draft—doesn't make any changes to the default behavior, and lets folks opt-in to include files they want. Might be nice later on to add some sugar:

- A shortcut for common patterns (e.g., `doomPackageDir = [ "init.el" "packages.el" "mod/" ] for filtering `doomPrivateDir`.
- Automatically creating the empty `config.el` if needed.
- A special case in nix-doom-emacs for the ("just take `init.el` and `packages.el` case, which I imagine ). This could be an exported function to apply to `./doom.d`.

If something like the above sounds good, let me know!

**Comment by ckiee** [comment]
`doomPackageDir` seems like a nice idea. Though default should be `doomPrivateDir` or `null`, not `""`. The third bullet point seems not-so-trivial to implement over all supported platforms so don't block on that for the PR. List sounds nice and auto `config.el` should probably come with a little warning.

**Comment by thiagokokada** [comment]
> If something like the above sounds good, let me know!

Sounds good to me. I wouldn't care to much about about adding the sugar, at least for a first PR.

Also concur that the default should be `null` and not `""`.

**Comment by patrickaldis** [comment]
Just wondering how I would go about enabling this? Can't find docs. Thanks for any help.
Is the idea that we now set `doomPackageDir` to a folder containing only `init.el` and `packages.el`

**Comment by znewman01** [comment]
Docs are only inline right now: https://github.com/nix-community/nix-doom-emacs/blob/c852431c25a9d2b8f9322505a38868d4cee6b8d6/default.nix#L3-L23

(#331 will probably document this somewhere better)

For an example, see how I'm using it: https://github.com/znewman01/dotfiles/blob/c1b35cdfb4ca15a22ab55587fac1116f6a87475a/emacs/default.nix#L6-L27

**Comment by akaihola** [comment]
>(#331 will probably document this somewhere better)

If I [searching for `doomPackageDir` in this repository](https://github.com/search?q=repo%3Anix-community%2Fnix-doom-emacs%20doomPackageDir&type=code), I can't actually find any documentation on it in the repository files.
