### ISSUE TITLE
Symbol’s function definition is void: doom-modeline-set-vcs-modeline

### ISSUE THREAD

**Issue by vtrf** [nix-community/nix-doom-emacs#309]
I'm currently receiving the error: `Symbol’s function definition is void: doom-modeline-set-vcs-modeline` when I run `SPC g g (magit-status)` on any project I have.

**nixpkgs**: `8ba120420fbdd9bd35b3a5366fa0206d8c99ade3`
**nix-doom-emacs**: `b65e204ce9d20b376acc38ec205d08007eccdaef`

Other users seem to be facing the same error: https://github.com/nix-community/nix-doom-emacs/issues/88#issuecomment-1279953533

**Comment by Kha** [comment]
I think this is a version mismatch between doom-modeline as pinned by doom-emacs and emacs-overlay: the function was removed in https://github.com/seagle0128/doom-modeline/commit/b596440ee78b3e7d2debc3d73f4d938d968fb896. A simple workaround is to copy that function into e.g. your `config.el`.

**Comment by thiagokokada** [comment]
We should probably pin the correct version of `doom-modeline` then.

I am trying to get NDE to build with a newer version of doom-emacs, but I hit a few issues that I need to investigate later. See #316.

**Comment by hab25** [comment]
> I think this is a version mismatch between doom-modeline as pinned by doom-emacs and emacs-overlay: the function was removed in [seagle0128/doom-modeline@b596440](https://github.com/seagle0128/doom-modeline/commit/b596440ee78b3e7d2debc3d73f4d938d968fb896). A simple workaround is to copy that function into e.g. your `config.el`.

If this is indeed the problem, solving it would additionally fix this other issue:

`Symbol’s function definition is void: doom-modeline-set-project-modeline`,

which happens on emacs initialization if `init.el` has:
```elisp
:ui
doom-dashboard
modeline ;; note the absence of `+light` flag
```

**Comment by thiagokokada** [comment]
With #319 merged this issue should be fixed. Please comment here otherwise and I will reopen the issue.
