### ISSUE TITLE
+doom-dashboard-init-h (void-function doom-modeline-set-project-modeline)

### ISSUE THREAD

**Issue by souxd** [nix-community/nix-doom-emacs#325]
Using emacs 28.2 NativeComp

I had to override doom-modeline to a different revision because the current nix-doom-emacs eglot pin would break without it https://github.com/doomemacs/doomemacs/commit/aa40daf5e8483a541f301e367430e1cae55423d8. But this change came at the cost of introducing a new modeline error on init:
`Error during redisplay: (doom-init-ui-h #<frame *scratch* – Doom Emacs 0x30b1938>) signaled (doom-hook-error doom-init-ui-hook +doom-dashboard-init-h (void-function doom-modeline-set-project-modeline))

flake.lock
https://pastebin.com/Uw40CtdP

**Comment by thiagokokada** [comment]
> 



> Using emacs 28.2 NativeComp
> 
> I had to override doom-modeline to a different revision because the current nix-doom-emacs eglot pin would break without it [doomemacs/doomemacs@aa40daf](https://github.com/doomemacs/doomemacs/commit/aa40daf5e8483a541f301e367430e1cae55423d8). But this change came at the cost of introducing a new modeline error on init: `Error during redisplay: (doom-init-ui-h #<frame _scratch_ – Doom Emacs 0x30b1938>) signaled (doom-hook-error doom-init-ui-hook +doom-dashboard-init-h (void-function doom-modeline-set-project-modeline))
> 
> flake.lock https://pastebin.com/Uw40CtdP

You shouldn't override the `doom-modeline`, it is there for one reason: #309. Until #316 is finished, this will be the situation unfortunately.

For now, my recommendation would be to try to pin `eglot` to a early version.

**Comment by thiagokokada** [comment]
I will try to remove the current `doom-modeline` pin and add this as an workaround: https://github.com/nix-community/nix-doom-emacs/issues/309#issuecomment-1288177426.

However not sure if this will work well.

If you want a recommendation from me, I particularly `(modeline +light)` instead that is faster and also much less bloated, and it basically avoids most of those issues.

**Comment by thiagokokada** [comment]
@souxd Can you try https://github.com/nix-community/nix-doom-emacs/pull/326 to see if it fixes your issue?

**Comment by souxd** [comment]
Oh yes it does fix my issue! Thank you mr. Kokada!

Closing this since my issue was fixed.

**Comment by thiagokokada** [comment]
#326 is merged, closing this issue.
