### ISSUE TITLE
`doom.d` directory only updates after rebuilding twice

### ISSUE THREAD

**Issue by bandithedoge** [nix-community/nix-doom-emacs#42]
For whatever reason whenever I change my `config.el`, `doom.d` in the Nix store does not update until I rebuild again.

`nix-info -m`:
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5.1`
 - channels(bandithedoge): `"darwin, home-manager, nixpkgs-22.05pre345869.46821ea01c8"`
 - channels(root): `"nixpkgs-22.05pre345869.46821ea01c8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by ulysses4ever** [comment]
Maybe I'm missing something but why would it change without a rebuild? Rebuild syncs your local copy of doom.d (e.g. somewhere in your home directory) to the one inside the store. The rest of Emacs works with the store copy of it.

**Comment by bandithedoge** [comment]
> Maybe I'm missing something but why would it change without a rebuild? Rebuild syncs your local copy of doom.d (e.g. somewhere in your home directory) to the one inside the store. The rest of Emacs works with the store copy of it.

It changes *only* after rebuilding *twice*.

**Comment by ulysses4ever** [comment]
Oh, missed that, sorry.

**Comment by ckiee** [comment]
That is extremely odd.. Steps taken to trigger it? Your configuration? Tested on NixOS?

**Comment by montchr** [comment]
This sounds a lot like a flake "gotcha" I've encountered a few times before (not specific to this particular flake). I'm guessing that OP figured this out already or took another direction, but I would also venture to guess that the path given to `doomPrivateDir` pointed to some location in the store, not in the flake itself. When that happens, upon rebuilding, Nix references the previous generation of the flake source, not to the current version of the files as they appear in your editor.

https://stackoverflow.com/questions/43850371/when-does-a-nix-path-type-make-it-into-the-nix-store-and-when-not/43850372#43850372

**Comment by thiagokokada** [comment]
> This sounds a lot like a flake "gotcha" I've encountered a few times before (not specific to this particular flake). I'm guessing that OP figured this out already or took another direction, but I would also venture to guess that the path given to `doomPrivateDir` pointed to some location in the store, not in the flake itself. When that happens, upon rebuilding, Nix references the previous generation of the flake source, not to the current version of the files as they appear in your editor.
> 
> https://stackoverflow.com/questions/43850371/when-does-a-nix-path-type-make-it-into-the-nix-store-and-when-not/43850372#43850372

It seems that this explains the issue. I am closing this issue.
