### ISSUE TITLE
Build fail on nix unstable branch

### ISSUE THREAD

**Issue by JM445** [nix-community/nix-doom-emacs#471]
I just switched from nix 22.11 to unstable branch, and nix-doom-emacs does not want to build anymore.

It fails on calling the 'derivationStrict' builtin. Actually it seems to be more or less the exact same error as in [this](https://github.com/nix-community/nix-doom-emacs/actions/runs/5205952265/jobs/9392213665) CI.

I'm not quite what we can call a nix developper, nor an elisp one so I can't figure out what is causing that problem. Is there a way-arround or nix-doom-emacs is just not compatible with unstable nix ?

**Comment by ckiee** [comment]
In the CI:
`error: fcitx-engines is deprecated, please use fcitx5 instead.`
which is:
https://github.com/nix-community/home-manager/issues/3814

Please send build logs or close this issue if that fixes it.
