### ISSUE TITLE
Requires native compilation?

### ISSUE THREAD

**Issue by hexagonal-sun** [nix-community/nix-doom-emacs#48]
Hi there,

When building my doom configuration I'm getting the following error:

```
# -*- lisp-interaction -*-
# vim: set ft=lisp:

(error "Emacs was not compiled with native compiler support (--with-native-compilation)")

(signal error ("Emacs was not compiled with native compiler support (--with-native-compilation)"))

(error "Emacs was not compiled with native compiler support (--with-native-compilation)")

(cond ((null (featurep 'native-compile)) (error "Emacs was not compiled with native compiler support (--with-native-compilat
ion)")) ((null (native-comp-available-p)) (error "Cannot find libgccjit library")))

(comp-ensure-native-compiler)

(native--compile-async "/nix/store/bdvd1fd1mmc4w1afyirfw794dx2z5qyh-straight-emacs-env/straight/build-29.0.50/auto-minor-mod
e/" recursively nil straight--native-compile-file-p)

(let ((load (not (not load)))) (native--compile-async files recursively load selector))

(native-compile-async "/nix/store/bdvd1fd1mmc4w1afyirfw794dx2z5qyh-straight-emacs-env/straight/build-29.0.50/auto-minor-mode
/" recursively nil straight--native-compile-file-p)

(straight--build-native-compile (:local-repo "auto-minor-mode" :repo "auto-minor-mode" :type git :package "auto-minor-mode")
)

(run-hook-with-args straight--build-native-compile (:local-repo "auto-minor-mode" :repo "auto-minor-mode" :type git :package
 "auto-minor-mode"))

(straight--build-package (:local-repo "auto-minor-mode" :repo "auto-minor-mode" :type git :package "auto-minor-mode") nil)
```

Does this mean that using nix-doom-emacs requires `emacsGcc`?  That would be a shame since for some machines (e.g. my raspberry pi) this means that building my configuration requires approx 6 hours.

**Comment by hexagonal-sun** [comment]
Sorry, I don't have my config uploaded publicly, but here is a zip of my `doom.d` config. 
[doom.d.tar.gz](https://github.com/nix-community/nix-doom-emacs/files/7963166/doom.d.tar.gz)

I invoke it with:

```nix
{ config, lib, pkgs, inputs, ... }:

let inherit (pkgs.stdenv.hostPlatform) isDarwin isLinux;
in
lib.mkMerge [
  {
    programs.doom-emacs = {
      enable = true;
      doomPrivateDir = ../doom.d;
      emacsPackage = pkgs.emacsGcc;
    };
  }
  (lib.mkIf isLinux {
    services.emacs = {
      enable = true;
    };
  })
]
```

If i change `emacsPackage` to `emacsGit`, I see the issue.

**Comment by ckiee** [comment]
Ooh! The `home-manager` module passes through the flake inputs. Maybe you accidentally bumped them? It does that [automagically](https://github.com/nix-community/nix-doom-emacs/actions/workflows/update-dependencies.yml) so you shouldn't have to.. 

I'll try building with `emacsGit` just for the hell of it

**Comment by ckiee** [comment]
Huh! I can reproduce with both `emacsGit` and `emacsUnstable` from the overlay (which you shouldn't be using manually!), just not `emacs` from nixpkgs: [`/nix/store/033cxal24xrp6nh6vfky9hs2jc1rn637-straight-emacs-env.drv`](https://i.ckie.dev/kqaN6AK.txt)

**Comment by hexagonal-sun** [comment]
Ah, so you're saying that I should not be importing `emacs-overlay` in my flake, but leave that to the `nix-doom-emacs` flake to select the right version of the emacs overlay?

**Comment by ckiee** [comment]
Yeah, but that still won't fix the original issue— I dunno why `emacs-overlay`'s emacses are broken.

**Comment by hexagonal-sun** [comment]
Hm, is it because the `nativecomp` branch would have been merged into master with those versions of Emacs, whereas it's not in master with nixpkg's

**Comment by ulysses4ever** [comment]
Sorry if I missed that but do you use relatively recent version of doom-emacs? There used to be [a similar issue upstream](https://github.com/hlissner/doom-emacs/issues/4947).

**Comment by hexagonal-sun** [comment]
Just had a look and it looks like I'm using `35865ef5e89442e3809b8095199977053dd4210f` according to my flake.lock.

**Comment by hexagonal-sun** [comment]
Ah, looks like there was a fix in `nix-straight` that fixes this?  Thanks for fixing that @ckiee!

**Comment by ckiee** [comment]
Yup, here: https://github.com/nix-community/nix-straight.el/commit/08d75e5651cb52f8a07e03408ed19e04bee07505. I probably should've linked that in the other commit's description.
