### ISSUE TITLE
Vertico is showing &nopath and is not working

### ISSUE THREAD

**Issue by Guisanpea** [nix-community/nix-doom-emacs#6]
First of all I want to mention that this project is amazing and I am finding the community very helpful so thanks a lot for your work.

I have been trying these days to set up emacs to work with sway (wayland) and I have done a combination of emacs-overlay with pgtk and gcc and this package.

You can find my doom config in https://github.com/Guisanpea/dotfiles/commit/a9fd3fa8de644c73ac800e92115aa84e2bba4863 and my nix flakes at https://github.com/Guisanpea/nixfiles

The problem I am having is that vertico, which is a really important package for me is not working. When I check doom status I see the following

```
generated    Dec 14, 2021 14:17:04
system       NixOS 21.11.20211130.96b4157 (Porcupine) Linux 5.10.81 x86_64 pgtk
emacs        29.0.50 master da2c0e8f7 /nix/store/fvp6wqmbzikypysdzwb5jwm7ipavw1rf-doom-emacs/ -> /nix/store/fvp6wqmbzikypysdzwb5jwm7ipavw1rf-doom-emacs/
doom         3.0.0-alpha fatal: not a git repository (or any of the parent directories): .git /nix/store/7h2nbf7fl2z9nvbza1hfnd273jaxwddi-doom-private/ -> /nix/store/7h2nbf7fl2z9nvbza1hfnd273jaxwddi-doom-private/
shell        /run/current-system/sw/bin/bash
features     CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS XIM GTK3 ZLIB
traits       gui server-running custom-file
custom       vc-annotate-very-old-color vc-annotate-color-map vc-annotate-background rustic-ansi-faces pdf-view-midnight-colors objed-cursor-color jdee-db-spec-breakpoint-face-colors jdee-db-requested-breakpoint-face-colors jdee-db-active-breakpoint-face-colors highlight-tail-colors fci-rule-color exwm-floating-border-color custom-safe-themes ansi-color-names-vector
modules      :completion company (&nopath vertico +icons) :ui doom doom-dashboard doom-quit hl-todo ligatures modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers syntax (spell +flyspell) grammar :tools (debugger +lsp) docker editorconfig (eval +overlay) lookup lsp :lang (elixir +lsp) emacs-lisp erlang json javascript markdown org php scala sh web yaml :config (default +bindings +smartparens)
```

I have the same doom config in ubuntu and nix and it is giving me problems only in ubuntu and one thing that worries me is that in info the vertico module appears as `(&nopath vertico +icons)`

What could be making that issue?

**Comment by ckiee** [comment]
> The problem I am having is that vertico, which is a really important package for me is not working

You [should elaborate](http://www.catb.org/esr/faqs/smart-questions.html) on "not working": [I use ivy](https://github.com/ckiee/nixfiles/blob/d5ca0b03dc3d085431d4c065e0e37ece4f3db528/ext/doom-conf/init.el#L26) so I haven't had a chance to hit this. 

Regardless, one guess would be that it might need `ripgrep` in PATH, which I [do](https://github.com/ckiee/nixfiles/blob/d5ca0b03dc3d085431d4c065e0e37ece4f3db528/modules/doom-emacs.nix#L6-L44) [2 links] [here](https://github.com/ckiee/nixfiles/blob/d5ca0b03dc3d085431d4c065e0e37ece4f3db528/modules/doom-emacs.nix#L97-L104).

**Comment by Guisanpea** [comment]
So now it is working and I am not really sure about what has changed. So I am going to close. If I have some more info I will tell.
Thank you
