### ISSUE TITLE
Using nix-doom-emacs in a doom-emacs config repository, without home-manager?

### ISSUE THREAD

**Issue by shaunsingh** [nix-community/nix-doom-emacs#68]
Hi, I have a separate repo for my doom configuration (https://github.com/shaunsingh/nyoom.emacs) and was wondering if its possible to build/run the configuration using nix? Ideally without using home-manager? The readme only specifies how to use it with home-manager

**Comment by ckiee** [comment]
I'm not sure how you would do it with a flake exactly, but in general you can remove a few lines from the home-manager example:
```diff
{ pkgs, ... }:

let
  doom-emacs = pkgs.callPackage (builtins.fetchTarball {
    url = https://github.com/nix-community/nix-doom-emacs/archive/master.tar.gz;
  }) {
    doomPrivateDir = ./doom.d;  # Directory containing your config.el init.el
                                # and packages.el files
  };
-in {
+in doom-emacs
-  home.packages = [ doom-emacs ];
-}
```

Crap. I can't stop the urge to figure it out.. Here's a [broken patch](https://i.ckie.dev/629jyHj.patch) that should give you a base to work off of.

**Comment by shaunsingh** [comment]
I tried this: 
```nix
{
  description = "shaunsingh's doom emacs configuration";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    nix-doom-emacs.url = "github:nix-community/nix-doom-emacs";
    emacs.url = "github:cmacrae/emacs";
    flake-utils.url  = "github:numtide/flake-utils";
  };

  outputs =
    { self
    , nixpkgs
    , emacs
    , flake-utils
    , nix-doom-emacs
    }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        overlays = [ (import emacs) ];
        pkgs = import nixpkgs {
          inherit system overlays;
        };
      in
      with pkgs;
      {
        defaultPackage = nix-doom-emacs.package.${system} { doomPrivateDir = ./.; };
      }
    );
}
```

Results in this error: `error: unable to execute '/nix/store/2yzavm1d79qwk52mb99bvlhsw1bffp0p-emacs-with-packages-27.2/bin/emacs-with-packages': No such file or directory`

Is it possible to change what emacs package nix-doom-emacs is using as well, from the overlay I'm using (or from the `emacs-overlay` nix-doom-emacs uses)? I didn't find anything in the README

**Comment by ckiee** [comment]
> `nix build` works fine, so that's a start

Yay! (^:

> `nix run` Results in this error 

It should be running `/nix/store/blahblah/bin/emacs` instead. Not sure how you make Nix do that.

> Is it possible to change what emacs package nix-doom-emacs is using as well

Sure, pass this in alongside `doomPrivateDir`: ([my usage here](https://github.com/ckiee/nixfiles/blob/95ce836dfebd8834aa1a5f0fdc2f86dc59eb7fff/modules/doom-emacs/default.nix#L76))
```nix
        emacsPackages = emacsOverlay.emacsPackagesFor someEmacsPackage;
```

**Comment by ckiee** [comment]
It seems like I have answered everything

**Comment by quinn-dougherty** [comment]
@shaunsingh's `flake.nix` above got me building a per-directory `emacs` in `result/bin` that seems to be responsive to my `doom.d` configuration (because I declared `coq` in `(doom! ... :lang ... coq)` and proof general was installed upon booting up emacs), but it's not doom -- no vim, no themes, no doom home screen. 

Here's my repo https://github.com/orbis-tertius/coq-tinyram it seems strange to me.

**Comment by ckiee** [comment]
So it's good now @quinn-dougherty?
